#
# ~/.bashrc
# 
# auth: fs
# date: 11-12-2010
#

# histfile settings
export HISTCONTROL=erasedups
export HISTSIZE=10000
shopt -s histappend

# misc

export EDITOR=/usr/bin/vim

alias ls='ls --color=auto'
